### ISSUE TITLE
ftrack 2ways Sync

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-ftrack#133]
SubEpic of [🚀 Prod Trackers 2ways Sync](https://github.com/ynput/AYON-Epics/issues/32)

## Strategy

ftrack addon must support two ways synchronization of all relevant data.
This includes syncronizing:
- [x] One way sync of User (https://github.com/ynput/ayon-ftrack/pull/151)
- [x] Entity attributes - anatomy and attributes values on entities (https://github.com/ynput/ayon-ftrack/issues/162)
- [x] Statuses (https://github.com/ynput/ayon-ftrack/issues/160)
- [x] Assignments (https://github.com/ynput/ayon-ftrack/issues/161)
- [x] Comments (https://github.com/ynput/ayon-ftrack/pull/173)

## Out of this epic scope
- [ ] Versions and Reviewables - Multiple reviewables will only be possible in AYON, and ftrack only takes the 1st one.  (https://github.com/ynput/ayon-ftrack/issues/164)
- [ ] Hierarchy changes - created/removed/renamed folders and tasks (https://github.com/ynput/ayon-ftrack/issues/163)
- [ ] Links ? [TBD]

For the start we'll only do one way for:
- [x] Entity hierarchy (anatomy and entities themselves)
- [x] Users
But with full intention to do two way sync for them in this epic as well

NOTE
- [x] To be able to support 2 way sync we need https://github.com/ynput/ayon-backend/issues/391 first.
- [x] To be able to support comments sync we need https://github.com/ynput/ayon-backend/issues/429 .

## Generic User Stories
(Applicable for each of the checkbox in the strategy section)
- As an Artist or Lead, when I [do something] in the production tracker, I want the changes to be visible in AYON.
- As an Artist or Lead, when I [do something] in AYON Activity Feed, I the changes to be visible in the production tracker.

* We will probably need multiple sync services for ftrack. 
* We need to be able to create a version without a representation.

**Comment by tanh609** [comment]
Hullo, https://github.com/ynput/ayon-ftrack/issues/125 might be relevant to this issue. 

@sjt-rvx have a very clever idea of having an option to customize/select attribute for the attribute sync.
